# Generated by Django 4.2.11 on 2024-03-26 10:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 26, 10, 53, 59, 160420, tzinfo=datetime.timezone.utc)),
        ),
    ]
