# Generated by Django 4.2.11 on 2024-03-26 19:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_categories_alter_article_pub_date_article_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 26, 19, 22, 37, 788374, tzinfo=datetime.timezone.utc)),
        ),
    ]
