# Generated by Django 4.2.11 on 2024-04-08 14:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_remove_categories_slug_alter_article_pub_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2024, 4, 8, 14, 26, 23, 236786, tzinfo=datetime.timezone.utc)),
        ),
    ]
