# Generated by Django 4.2.11 on 2024-04-16 11:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_alter_article_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2024, 4, 16, 11, 32, 26, 490933, tzinfo=datetime.timezone.utc)),
        ),
    ]
